# Generated by Django 5.0.2 on 2024-03-04 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('price', models.PositiveSmallIntegerField(verbose_name='Price')),
                ('description', models.TextField(max_length=255, verbose_name='Description')),
                ('color', models.CharField(max_length=255, verbose_name='Color')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category', verbose_name='Category')),
            ],
        ),
    ]
