# Generated by Django 5.0.2 on 2024-03-05 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(default=1, upload_to='', verbose_name='Photo'),
            preserve_default=False,
        ),
    ]
