# Generated by Django 5.0.2 on 2024-03-04 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name': 'Services', 'verbose_name_plural': 'Services"'},
        ),
    ]
