# Generated by Django 5.0.2 on 2024-03-05 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0003_rename_home_cosmetics'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cosmetics',
            options={'verbose_name': 'Services', 'verbose_name_plural': 'Services'},
        ),
    ]
